dist: trusty
sudo: off
language: python
addons:
  apt:
    packages:
      - cifs-utils
      - libssl-dev
      - libffi-dev
      - python-dev
install:
  - mkdir $HOME/share
  - if [ $STORAGE_ACCOUNT_KEY ]; then sudo mount -t cifs //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${STORAGE_SHARE_NAME} $HOME/share -o vers=3.0,username=${STORAGE_ACCOUNT_NAME},password=${STORAGE_ACCOUNT_KEY},dir_mode=0777,file_mode=0777,serverino || sudo mount -t cifs //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${STORAGE_SHARE_NAME} $HOME/share -o vers=3.0,username=${STORAGE_ACCOUNT_NAME},password=${STORAGE_ACCOUNT_KEY},dir_mode=0777,file_mode=0777,serverino; fi
jobs:
  include:
    - stage: build
      script: ./scripts/ci/build.sh
    - stage: verify
      env: PURPOSE='Automation'
      script: ./scripts/ci/test_automation.sh
      python: 3.6
    - stage: verify
      env: PURPOSE='Automation'
      script: ./scripts/ci/test_automation.sh
      python: 2.7
    - stage: verify
      script: ./scripts/ci/test_static.sh
      env: PURPOSE='Static Check'
      python: 3.6
    - stage: verify
      script: ./scripts/ci/test_integration.sh
      env: PURPOSE='Integration'
      python: 3.6
    - stage: verify
      script: ./scripts/ci/test_integration.sh
      env: PURPOSE='Integration'
      python: 2.7
    - stage: publish
      script: ./scripts/ci/publish.sh
